services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sre-bootcamp-network

  migrate:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - sre-bootcamp-network

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
      BIND_ADDRESS: :8080
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - migrate
    networks:
      - sre-bootcamp-network

volumes:
  postgres_data:

networks:
  sre-bootcamp-network:
    driver: bridge
