version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: studentapiuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentapidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sre-bootcamp-network

  migrate:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://studentapiuser:password@db:5432/studentapidb?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - sre-bootcamp-network

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://studentapiuser:password@db/studentapidb?sslmode=disable
      BIND_ADDRESS: :8080
    depends_on:
      - db
      - migrate
    networks:
      - sre-bootcamp-network

volumes:
  postgres_data:

networks:
  sre-bootcamp-network:
    driver: bridge
