name: Sre Bootcamp CICD Pipeline

on:
  push:
    paths:
      - "**/*"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [self-hosted, macos]

    services:
      postgress:
        image: postgres:13
        env:
          POSTGRES_USER: studentapiuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: studentapid
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ env.POSTGRES_USER  }}" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build . -t student-api

      - name: Run Lint
        run: golint ./... || true

      - name: Push to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag student-api:latest $DOCKER_USER/student-api:latest
          docker push $DOCKER_USER/student-api:latest
