name: Sre Bootcamp CICD

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: Run tests
        run: make test

      - name: Run code linting
        run: |
          go fmt ./...
          go vet ./...

  docker:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: make docker-build

      - name: Push Docker image
        run: docker push your-docker-repo/student-api:latest
