name: Sre Bootcamp CICD Pipeline

on:
  push:
    paths:
      - "**/*"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [self-hosted, macos]

    env:
      POSTGRES_USER: studentapiuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studentapidb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17.0"
      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: ${{ env.POSTGRES_USER }}
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
          PGDATABASE: ${{ env.POSTGRES_DB }}
        run: |
          psql -c 'CREATE DATABASE studentapidb;' || true
          go test ./...

      - name: Build Docker image
        run: docker build . -t student-api

      - name: Docker Login and Push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker tag student-api:latest $DOCKER_USER/student-api:latest
          docker push $DOCKER_USER/student-api:latest
