name: Sre Bootcamp CICD

on: [push]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run tests
        run: make test

      - name: Run code linting
        run: |
          go fmt ./...
          go vet ./...
